# Generated by Django 4.2.7 on 2023-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'CallbackRequests',
            },
        ),
    ]
