# Generated by Django 4.2.7 on 2023-11-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='products_photos')),
            ],
            options={
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.AlterModelOptions(
            name='informationblocks',
            options={'verbose_name_plural': 'Information blocks - section 3'},
        ),
    ]
