# Generated by Django 4.2.7 on 2023-11-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_photos_alter_informationblocks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationblocks',
            name='link_href',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='informationblocks',
            name='link_text',
            field=models.TextField(blank=True),
        ),
    ]
