# Generated by Django 4.2.7 on 2023-11-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_informationblocks_link_href_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'CallbackRequests',
            },
        ),
    ]
