# Generated by Django 4.2.7 on 2023-11-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_importantinformation_informationcircles_otherlinks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformationBlocks',
        ),
        migrations.AlterModelOptions(
            name='ratestable',
            options={'verbose_name_plural': 'RatesTable'},
        ),
    ]
