# Generated by Django 4.2.7 on 2023-11-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_informationcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('first', models.TextField()),
                ('second', models.TextField()),
                ('third', models.TextField()),
                ('fourth', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TableRows',
            },
        ),
    ]
