# Generated by Django 4.2.7 on 2023-11-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_tablerows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatesTable',
        ),
        migrations.AlterField(
            model_name='tablerows',
            name='first',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tablerows',
            name='fourth',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tablerows',
            name='second',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tablerows',
            name='third',
            field=models.TextField(blank=True),
        ),
    ]
