# Generated by Django 4.2.7 on 2023-11-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_ratestable_alter_tablerows_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherlinks',
            name='display',
            field=models.TextField(blank=True),
        ),
    ]
