# Generated by Django 4.2.7 on 2023-11-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_processesblocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacyblocks',
            options={'verbose_name_plural': 'PrivacyBlocks'},
        ),
        migrations.AlterModelOptions(
            name='processesblocks',
            options={'verbose_name_plural': 'ProcessesBlocks'},
        ),
        migrations.RemoveField(
            model_name='processesblocks',
            name='align',
        ),
    ]
