# Generated by Django 4.2.7 on 2023-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_privacyblocks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerows',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
