# Generated by Django 4.2.7 on 2023-11-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_tablerows_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacyblocks',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
