# Generated by Django 4.2.7 on 2023-11-20 10:53

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_processesblocks_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', django_ckeditor_5.fields.CKEditor5Field(max_length=500, verbose_name='Краткое описание')),
                ('full_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полное описание')),
            ],
        ),
    ]
