# Generated by Django 4.2.7 on 2023-11-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
