# Generated by Django 4.2.7 on 2023-11-20 17:49

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processescards',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='processescards',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
