# Generated by Django 4.2.7 on 2023-11-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_processescards_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processescards',
            name='link_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processescards',
            name='link_url',
            field=models.TextField(blank=True),
        ),
    ]
