# Generated by Django 4.2.7 on 2023-11-20 19:46

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_processescards_link_title_processescards_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinformation',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
