# Generated by Django 4.2.7 on 2023-11-20 20:56

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_processesblocks_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeableInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('info', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name_plural': 'ChangeableInformation',
            },
        ),
    ]
